name: gym_tracker_flutter
description: GymDiary mobile app.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # page_turn: ^1.0.1

  cupertino_icons: ^1.0.6
  flutter_animator: ^3.2.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  flutter_speed_dial: ^7.0.0
  intl: ^0.18.1
  page_transition: ^2.1.0
  flutter_typeahead: ^4.8.0
  provider: ^6.1.1
  fl_chart: ^0.64.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
dev_dependencies:
  flutter_test:
    
    sdk: flutter
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
