name: gym_tracker_flutter
description: GymDiary mobile app.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # page_turn: ^1.0.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  failure_stack: ^0.1.3
  cupertino_icons: ^1.0.6
  flutter_animator: ^3.2.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  flutter_speed_dial: ^7.0.0
  intl: ^0.19.0
  page_transition: ^2.1.0
  build_runner: ^2.4.11
  flutter_typeahead: ^5.1.7
  provider: ^6.1.1
  fl_chart: ^0.68.0
  flutter_bloc: ^8.1.3
  get_it: ^7.7.0
  slide_to_act: ^2.0.2
  dio: ^5.4.3+1
  injectable: ^2.4.2
  injectable_generator: ^2.6.1
  logger: ^2.3.0



dev_dependencies:
  flutter_test:
    
    sdk: flutter
  shared_preferences: ^2.2.2
flutter:
  uses-material-design: true

  assets:
    - assets/images/
